@echo off
setlocal enabledelayedexpansion

echo ============================================================
echo  SAML Interceptor -- Build
echo ============================================================

:: ── Locate Python ────────────────────────────────────────────────────────────
set PY=
where python >nul 2>&1 && set PY=python
if not defined PY (
    set _C=%LOCALAPPDATA%\Programs\Python\Python314\python.exe
    if exist "!_C!" set PY="!_C!"
)
if not defined PY (
    echo [ERROR] Python not found. Install Python 3.10+ from https://python.org
    pause & exit /b 1
)
for /f "tokens=*" %%v in ('!PY! --version 2^>^&1') do echo [+] %%v

:: ── Read VERSION ─────────────────────────────────────────────────────────────
if not exist VERSION (
    echo [ERROR] VERSION file not found.
    pause & exit /b 1
)
set /p VERSION=<VERSION
set VERSION=%VERSION: =%
echo [+] Version: %VERSION%

:: Split into integers for Windows version quad
for /f "tokens=1,2,3 delims=." %%a in ("%VERSION%") do (
    set VER_MAJ=%%a
    set VER_MIN=%%b
    set VER_PAT=%%c
)
if not defined VER_MAJ set VER_MAJ=0
if not defined VER_MIN set VER_MIN=0
if not defined VER_PAT set VER_PAT=0

:: ── Write _version.py (imported by the app for its title bar) ────────────────
(
    echo # Auto-generated by build_saml_interceptor.bat -- do not edit manually.
    echo __version__ = '%VERSION%'
) > _version.py
echo [+] _version.py written

:: ── Generate version_info.txt for PyInstaller exe metadata ───────────────────
(
    echo VSVersionInfo^(
    echo   ffi=FixedFileInfo^(
    echo     filevers=^(%VER_MAJ%, %VER_MIN%, %VER_PAT%, 0^),
    echo     prodvers=^(%VER_MAJ%, %VER_MIN%, %VER_PAT%, 0^),
    echo     mask=0x3f, flags=0x0, OS=0x40004,
    echo     fileType=0x1, subtype=0x0, date=^(0, 0^),
    echo   ^),
    echo   kids=[
    echo     StringFileInfo^([
    echo       StringTable^('040904B0', [
    echo         StringStruct^('FileDescription',  'SAML Interceptor'^),
    echo         StringStruct^('FileVersion',      '%VERSION%'^),
    echo         StringStruct^('InternalName',     'SAMLInterceptor'^),
    echo         StringStruct^('OriginalFilename', 'SAMLInterceptor.exe'^),
    echo         StringStruct^('ProductName',      'SAML Interceptor'^),
    echo         StringStruct^('ProductVersion',   '%VERSION%'^),
    echo       ]^)
    echo     ]^),
    echo     VarFileInfo^([VarStruct^('Translation', [1033, 1200]^)]^)
    echo   ]
    echo ^)
) > version_info.txt
echo [+] version_info.txt written

:: ── Install / upgrade dependencies ───────────────────────────────────────────
echo.
echo [*] Checking dependencies...
!PY! -m pip install --quiet --upgrade cryptography pyinstaller pillow bandit
if errorlevel 1 ( echo [ERROR] pip install failed & pause & exit /b 1 )
echo [+] Dependencies OK

:: ── Security scan (bandit) ────────────────────────────────────────────────────
echo.
echo [*] Running security scan...
!PY! -m bandit -r saml_interceptor.py -ll --quiet
if errorlevel 1 ( echo [WARN] bandit reported issues -- review before distributing. ) else ( echo [+] Security scan clean )

:: ── Convert icon (saml.jpg -> saml.ico) ──────────────────────────────────────
if exist saml.jpg (
    echo [*] Converting icon...
    !PY! -c "from PIL import Image; img=Image.open('saml.jpg').convert('RGBA'); img.save('saml.ico', format='ICO', sizes=[(256,256),(128,128),(64,64),(48,48),(32,32),(16,16)])"
    if errorlevel 1 ( echo [WARN] Icon conversion failed, building without icon. ) else ( echo [+] saml.ico generated )
)

:: ── Clean previous build ─────────────────────────────────────────────────────
echo.
echo [*] Cleaning previous build...
if exist dist  rmdir /s /q dist
if exist build rmdir /s /q build

:: ── Run PyInstaller ──────────────────────────────────────────────────────────
echo.
echo [*] Running PyInstaller...
!PY! -m PyInstaller saml_interceptor.spec --noconfirm
if errorlevel 1 ( echo. & echo [ERROR] PyInstaller failed. & pause & exit /b 1 )

:: ── Rename output exe with version tag ──────────────────────────────────────
set OUT=SAMLInterceptor_v%VERSION%.exe
if not exist "dist\SAMLInterceptor.exe" (
    echo [ERROR] dist\SAMLInterceptor.exe not found.
    pause & exit /b 1
)
move /y "dist\SAMLInterceptor.exe" "%OUT%" >nul

:: Clean build artefacts
rmdir /s /q dist
rmdir /s /q build
del /f /q version_info.txt

:: ── Done ─────────────────────────────────────────────────────────────────────
echo.
echo ============================================================
for %%F in (%OUT%) do echo   %%~nxF   ^(%%~zF bytes^)
echo ============================================================
echo.
echo  To bump the version, edit VERSION and rebuild.
echo.
pause
