# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for SAMLInterceptor
# Build: pyinstaller saml_interceptor.spec

block_cipher = None

a = Analysis(
    ['saml_interceptor.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        # cryptography Rust/cffi internals PyInstaller misses
        'cryptography.hazmat.bindings._rust',
        'cryptography.hazmat.bindings._rust.x509',
        'cryptography.hazmat.backends.openssl',
        'cryptography.hazmat.backends.openssl.backend',
        'cryptography.hazmat.primitives.asymmetric.padding',
        'cryptography.hazmat.primitives.serialization.pkcs12',
        'cryptography.x509.extensions',
        'cryptography.x509.oid',
        # tkinter on Windows sometimes needs explicit inclusion
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        '_tkinter',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Trim unused heavy packages to keep the exe smaller
        'numpy', 'pandas', 'scipy', 'matplotlib',
        'PIL', 'PyQt5', 'PyQt6', 'wx',
        'IPython', 'jupyter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SAMLInterceptor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # no black console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Request UAC prompt so certutil + registry writes succeed
    uac_admin=False,        # HKCU registry + certutil -user don't need admin
    version='version_info.txt',   # generated by build script from VERSION file
    icon='saml.ico',              # generated by build script from saml.jpg
)
